<?php

namespace Helper\Config;

class FileSytem
{
    const CONFIG_FILE = DIRECTORY_SEPARATOR . 'config.json';

    const DATA_FOLDER_PATH =  DIRECTORY_SEPARATOR . 'tests' . DIRECTORY_SEPARATOR . '_data' . DIRECTORY_SEPARATOR;

    const CUSTOMER_DATA_FOLDER_PATH = self::DATA_FOLDER_PATH . 'Customer' . DIRECTORY_SEPARATOR;

    const LOCATOR_FOLDER_PATH = self::DATA_FOLDER_PATH . 'Locator' . DIRECTORY_SEPARATOR;

    const SHOP_SYSTEM_LOCATOR_FOLDER_PATH = self::LOCATOR_FOLDER_PATH . 'ShopSystem' . DIRECTORY_SEPARATOR;

    const PAYMENT_METHOD_LOCATOR_FOLDER_PATH = self::LOCATOR_FOLDER_PATH . 'PaymentMethod' . DIRECTORY_SEPARATOR;

    const PAYMENT_METHOD_DATA_FOLDER_PATH = self::DATA_FOLDER_PATH . 'PaymentMethodData' . DIRECTORY_SEPARATOR;

    const PAYMENT_METHOD_CONFIG_FOLDER_PATH = self::DATA_FOLDER_PATH . 'PaymentMethodConfig' . DIRECTORY_SEPARATOR;
}